// app/layout.tsx
import "./globals.css";

import { Inter } from "next/font/google";
import Link from "next/link";
import Logo from "@/components/branding/Logo";
import { Providers } from "@/components/_contexts/Providers";
import tw from "tailwind-styled-components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NavWrapper = tw.header`
  h-20
`;

const Nav = tw.nav`
  fixed
  w-full
  flex
  flex-row
  bg-gray-200 dark:bg-gray-900
  shadow-md
  gap-24
  p-2
  z-50
`;

const HomeLink = tw.a`
  flex
  items-center
  p-2
`;

const Menu = tw.ul`
  flex-grow
  flex
  flex-row
  gap-4
  items-center
`;

const MenuItem = tw.li`
  p-2
  hover:bg-gray-500/10
`;

const ContentWrapper = tw.div`
  bg-white/30 dark:bg-black/50
  w-full
  overflow-auto
  h-screen
  pb-24
`;

const Body = tw.body`
  relative
  h-screen
  w-screen
  overflow-hidden
`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Body className={inter.className}>
        <Providers>
          <NavWrapper>
            <Nav>
              <HomeLink $as={Link} href="/">
                <Logo />
              </HomeLink>
              <Menu>
                <MenuItem>
                  <Link href="/records">Records</Link>
                </MenuItem>
                <MenuItem>
                  <Link href="/about">About</Link>
                </MenuItem>
              </Menu>
            </Nav>
          </NavWrapper>
          <ContentWrapper>{children}</ContentWrapper>
        </Providers>
      </Body>
    </html>
  );
}
